poke_homepage:
    path:     /
    type:     annotations
    resource: PokeBundle\Controller\DefaultController

poke_rest:
    path: /api/
    type:     rest
    resource: PokeBundle\Controller\RestController

