imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PokeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

    pokepedia:
      pokedex:
          id: 2
      redis.databases:
          pokemons: 0
          types: 1
      types:
          colors:
            normal: '#A8A878'
            fire: '#F08030'
            fighting: '#C03028'
            water: '#6890F0'
            flying: '#A890F0'
            grass: '#78C850'
            poison: '#A040A0'
            electric: '#F8D030'
            ground: '#E0C068'
            psychic: '#F85888'
            rock: '#B8A038'
            ice: '#98D8D8'
            bug: '#A8B820'
            dragon: '#7038F8'
            ghost: '#705898'
            dark: '#705848'
            steel: '#B8B8D0'
            fairy: '#EE99AC'

# Endroid Twitter params
endroid_twitter:
    consumer_key: '%consumer_key%'
    consumer_secret: '%consumer_secret%'
    access_token: '%access_token%'
    access_token_secret: '%access_token_secret%'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Redis Configuration
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:        [ 'PokeBundle' ]

    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.css'
            filters: [cssrewrite]

        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"

        jquery:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.js'